backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "_source/assets/images/uploads" # Media files will be stored in the repo under _source/assets/images/uploads
public_folder: "/assets/images/uploads" # The src attribute for uploaded media will begin with /assets/images/uploads

collections:
  - name: "services" # Used in routes, e.g., /admin/collections/services
    label: "Services" # Used in the UI
    folder: "_source/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'A slug can have no spaces or special characters']}
      - {label: "Order", name: "order", widget: "number", value_type: "int", min: 1, max: 10}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Benefits Title", name: "benefits_title", widget: "string", default: "Pourquoi choisir mes services ?"}
      - label: "Benefits"
        name: "benefits"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
      - {label: "Closing Text", name: "closing_text", widget: "text"}
      - {label: "CTA Text", name: "cta_text", widget: "string", default: "J'exprime mon besoin"}
      - {label: "Testimonials Title", name: "testimonials_title", widget: "string", default: "Témoignages clients"}
      - {label: "Animation Direction", name: "animation_direction", widget: "select", options: ["top", "right", "bottom", "left"]}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_source/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog-post.html"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"], allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_source/_data/homepage.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Slogan", name: "slogan", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image Alt Text", name: "image_alt", widget: "string"}
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Services"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Icon", name: "icon", widget: "select", options: ["transition", "consulting", "coaching", "formation"]}
                  - {label: "Color", name: "color", widget: "select", options: ["light-blue", "dark-blue"]}
                  - {label: "Details", name: "details", widget: "markdown"}
          - label: "Expertise Section"
            name: "expertise"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Cards"
                name: "cards"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Color", name: "color", widget: "select", options: ["dark-blue", "medium-blue", "light-blue"]}
          - label: "Testimonials Section"
            name: "testimonials"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Featured Posts"
                name: "featured_posts"
                widget: "list"
                fields:
                  - {label: "Client", name: "client", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Excerpt", name: "excerpt", widget: "text"}
                  - {label: "Logo", name: "logo", widget: "image", required: false}
      - label: "Site Settings"
        name: "site"
        file: "_source/_data/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}